{% set version = '1.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmarkdown
  version: {{ version|replace("-", "_") }}

source:
  fn: rmarkdown_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rmarkdown_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rmarkdown/rmarkdown_{{ version }}.tar.gz
  sha256: 8765875573a29622c822c6a6ab0c93afe418b49bf7aec0ba0dd3c55b7e81175d


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 2

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: shiny (>= 0.11), tufte, testthat, digest, tibble
requirements:
  build:
    - r-base
    - r-base64enc
    - r-catools
    - r-evaluate >=0.8
    - r-htmltools >=0.3.5
    - r-jsonlite
    - r-knitr >=1.14
    - r-rprojroot
    - r-stringr >=1.2.0
    - r-yaml >=2.1.5

  run:
    - r-base
    - r-base64enc
    - r-catools
    - r-evaluate >=0.8
    - r-htmltools >=0.3.5
    - r-jsonlite
    - r-knitr >=1.14
    - r-rprojroot
    - r-stringr >=1.2.0
    - r-yaml >=2.1.5

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rmarkdown')"           # [not win]
    - "\"%R%\" -e \"library('rmarkdown')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://rmarkdown.rstudio.com
  license: GPL-3
  summary: Convert R Markdown documents into a variety of formats.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mdehollander
    - jdblischak
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rmarkdown
# Type: Package
# Title: Dynamic Documents for R
# Version: 1.6
# Authors@R: c( person("JJ", "Allaire", role = c("aut", "cre"), email = "jj@rstudio.com"), person("Joe", "Cheng", role = "aut", email = "joe@rstudio.com"), person("Yihui", "Xie", role = "aut", email = "yihui@rstudio.com"), person("Jonathan", "McPherson", role = "aut", email = "jonathan@rstudio.com"), person("Winston", "Chang", role = "aut", email = "winston@rstudio.com"), person("Jeff", "Allen", role = "aut", email = "jeff@rstudio.com"), person("Hadley", "Wickham", role = "aut", email = "hadley@rstudio.com"), person("Aron", "Atkins", role = "aut", email = "aron@rstudio.com"), person("Rob", "Hyndman", role = "aut", email = "Rob.Hyndman@monash.edu"), person("Ruben", "Arslan", role = "aut", email = "ruben.arslan@uni-goettingen.de"), person(family = "RStudio, Inc.", role = "cph"), person(family = "jQuery Foundation", role = "cph", comment = "jQuery library"), person(family = "jQuery contributors", role = c("ctb", "cph"), comment = "jQuery library; authors listed in inst/rmd/h/jquery-AUTHORS.txt"), person(family = "jQuery UI contributors", role = c("ctb", "cph"), comment = "jQuery UI library; authors listed in inst/rmd/h/jqueryui-AUTHORS.txt"), person("Mark", "Otto", role = "ctb", comment = "Bootstrap library"), person("Jacob", "Thornton", role = "ctb", comment = "Bootstrap library"), person(family = "Bootstrap contributors", role = "ctb", comment = "Bootstrap library"), person(family = "Twitter, Inc", role = "cph", comment = "Bootstrap library"), person("Alexander", "Farkas", role = c("ctb", "cph"), comment = "html5shiv library"), person("Scott", "Jehl", role = c("ctb", "cph"), comment = "Respond.js library"), person("Ivan", "Sagalaev", role = c("ctb", "cph"), comment = "highlight.js library"), person("Greg", "Franko", role = c("ctb", "cph"), comment = "tocify library"), person("Eli", "Grey", role = c("ctb", "cph"), comment = "FileSaver library"), person("John", "MacFarlane", role = c("ctb", "cph"), comment = "Pandoc templates"), person(family = "Google, Inc.", role = c("ctb", "cph"), comment = "ioslides library"), person("Dave", "Raggett", role = "ctb", comment = "slidy library"), person(family = "W3C", role = "cph", comment = "slidy library"), person("Dave", "Gandy", role = c("ctb", "cph"), comment = "Font-Awesome"), person("Ben", "Sperry", role = "ctb", comment = "Ionicons"), person(family = "Drifty", role = "cph", comment = "Ionicons"), person("Aidan", "Lister", role = c("ctb", "cph"),  comment = "jQuery StickyTabs") )
# Description: Convert R Markdown documents into a variety of formats.
# Depends: R (>= 3.0)
# Imports: tools, utils, knitr (>= 1.14), yaml (>= 2.1.5), htmltools (>= 0.3.5), caTools, evaluate (>= 0.8), base64enc, jsonlite, rprojroot, methods, stringr (>= 1.2.0)
# Suggests: shiny (>= 0.11), tufte, testthat, digest, tibble
# SystemRequirements: pandoc (>= 1.12.3) - http://pandoc.org
# URL: http://rmarkdown.rstudio.com
# License: GPL-3
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-15 12:12:24 UTC; jjallaire
# Author: JJ Allaire [aut, cre], Joe Cheng [aut], Yihui Xie [aut], Jonathan McPherson [aut], Winston Chang [aut], Jeff Allen [aut], Hadley Wickham [aut], Aron Atkins [aut], Rob Hyndman [aut], Ruben Arslan [aut], RStudio, Inc. [cph], jQuery Foundation [cph] (jQuery library), jQuery contributors [ctb, cph] (jQuery library; authors listed in inst/rmd/h/jquery-AUTHORS.txt), jQuery UI contributors [ctb, cph] (jQuery UI library; authors listed in inst/rmd/h/jqueryui-AUTHORS.txt), Mark Otto [ctb] (Bootstrap library), Jacob Thornton [ctb] (Bootstrap library), Bootstrap contributors [ctb] (Bootstrap library), Twitter, Inc [cph] (Bootstrap library), Alexander Farkas [ctb, cph] (html5shiv library), Scott Jehl [ctb, cph] (Respond.js library), Ivan Sagalaev [ctb, cph] (highlight.js library), Greg Franko [ctb, cph] (tocify library), Eli Grey [ctb, cph] (FileSaver library), John MacFarlane [ctb, cph] (Pandoc templates), Google, Inc. [ctb, cph] (ioslides library), Dave Raggett [ctb] (slidy library), W3C [cph] (slidy library), Dave Gandy [ctb, cph] (Font-Awesome), Ben Sperry [ctb] (Ionicons), Drifty [cph] (Ionicons), Aidan Lister [ctb, cph] (jQuery StickyTabs)
# Maintainer: JJ Allaire <jj@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-06-15 18:16:52 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
