travis:
  secure:
    BINSTAR_TOKEN: Dxna5TK+WCm/kEe6cHMjQ5exNS9sZn9sbUxZlQD22tyk8AEAkrpx43nPoGigxDxBOcVltEQ+zHRPAzpAJ2V0yIe2DDprCWzUWhCge7iQG8IrrKnkT+wLVeiEf8v1QPVhm+tbT+s2+GfSVafw2c3JJQXdvnV/uEkq+/Lts6xeLDK97VN6yo98+gciCH2+MRuO0NuGZ338TwQAFzhxDuL87S2KxSXdTWZQHQA7pMgxQBr4AmwoMg+oHw0RtJ3duJrWnswmyse6wbM8I2CE0iqv0vQUNyJCZ/iSHTA+D5DsKpkuhH79+ctSUptCOO6E/nyYOt1l3fh7z8+ThAIkaXZbPRZlBrPeVUZmvtVHjel0WgO7W6rIKwMMx1n06jXhCcXSnHtytmMvjYmjZBDaY7a0tvBOf4IdR0kuNsQRrl1lGDQc7qGPnQvNnCYVOqzc1qiT352bVq8N0s3UaGPFef4Bh2X9tulCHmE6DmcT+7Yum8+cAui09iaZ18o3d4Wl30v3Whp7c0OEH7Dycvx6KnkeBKabGYELgZy+mZ9L67cigOrrPKEzConDWUc9pecfhHQiLljGmES23LnCNYo1GD7Z4egFqT28+KIwzxnjptJZcZUXK/QZyH1+F45+Nb5SEUWS5q6CF0gigbFst5P3/bKJAUZPh75yKKgMTz1TZxBp3ts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
