travis:
  secure:
    BINSTAR_TOKEN: hFEVNEMp0ViQcQLKrO3/5IiQrqk6RR9u7iJOfXKo1OHMyzUbCSL/Jztx9pN54iEciuvda8X8KRpGBnh8jPd4ZRaaSCalgSPpsm2l/QnOJjCC3ZqZSW0w1q6gKFRBY6r5JQ3Cy7eLsswjaQZUfV11Cqn5fnhbjEXwkuO29bkf0e9PFOf8hHH6FcfT/tAh1w+MqYZl7TGBotx/gV501qbBiVhiXSyVWTziyqFWm+PgTEw/uC9v4VdG4CGyPIGEv5YmeCqPgTuLv13JzdBrUUiP2rywBJcUtrlbgG/fDjD1rpY3uigmq7dxOJWQ1HzqGFtBToytrq+Z8c1A8BseQWaRJIZdk7a/Je0/R2vFQh6HZuavFQilO2dS85aBVYfwXmql8GnW1aoi3ObHP/jnzIv33znCkIqzOyp3CdI9MZFSqf4/yNNdELGQmF7rUf0DqGOMAUmoq9Ob9wiQNlTphMlCUH9I3JJ1IV63IV0YwcQtAEbAE8HY2+TAqaMEjknB+pBcuNL/NsRyLjdD6xLlxuB/dz2pzCkfyYRI5+wf9rnwURnGiPrFOQ6zHZKDZM6KfGJu4SmMoWoTNqJnzSxAv1SwzE5UjYTkp7Qr2pmEgYnvtH8PaAy+oejQxrEINPdYc1xKUvsh3tarwGR0/qeXA1kLgZ+6MGpP7j7af+5ItMeDkJU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
